In [57]:
from RouteAlgorithm import *
import pandas as pd
import numpy as np

In [58]:
df_santa = pd.read_csv('santas_logistics.csv')
df_santa[:10]

,Child_ID,Name,Age,Location,Latitude,Longitude,Country,Gift_Preference,Listened_To_Parents,School_Grades,Good_Deed,Bad_Deed
0,1,Roman,12,Ban Pa Sak,16.8477,100.2563,Thailand,Door Basketball Hoop,0.721255,67.803632,Volunteered at thrift store,Damaged school awards
1,2,Yui,5,The Nation / La Nation,45.3500,-75.0333,Canada,Rhythm Tambourine,0.669235,NaN,Picked up trash at playground,NaN
2,3,Kento,9,Mealhada,40.3833,-8.4500,Portugal,School House Pack,0.863656,65.154011,Organized school outdoor equipment,Stole school materials
3,4,Irina,5,Lower Pottsgrove,40.2537,-75.5975,United States,Wireless Headphones,0.701440,NaN,Helped set up band challenge,NaN
4,5,Corina,10,Bayugan,8.7100,125.7500,Philippines,Rocket Building Set,0.799672,61.740031,Helped parent with dishes,Stole school materials
5,6,Calliope,11,Castel Volturno,41.0500,13.9167,Italy,Beauty Salon Set,0.868717,72.521423,Made birthday cards for classmates,Damaged school awards
6,7,Anamaria,7,Zdzieszowice,50.4192,18.1236,Poland,Music Mixing Set,0.776364,NaN,Helped organize writing center,Cheated in tournament
7,8,Ileana,9,Tortolì,39.9333,9.6500,Italy,Cooking Master Kit,0.513277,84.732606,Made cards for librarians,Lied about occurrences
8,9,Feng,5,Svobodnyy,51.4000,128.1000,Russia,Performance Microphone,0.523516,NaN,Picked up trash at bus stop,NaN
9,10,Hui,12,Paraibuna,-23.3861,-45.6622,Brazil,Diamond Dig Set,0.614100,91.233968,Helped parent with organizing toys,Stole school supplies

In [59]:
route_finder = RouteAlgorithm(df_santa)

# rename the columns Latitude and Longitude to X Coordinate and Y Coordinate
df_santa = df_santa.rename(columns={'Latitude': 'X Coordinate', 'Longitude': 'Y Coordinate'})

In [60]:
df_santa[:10]

,Child_ID,Name,Age,Location,X Coordinate,Y Coordinate,Country,Gift_Preference,Listened_To_Parents,School_Grades,Good_Deed,Bad_Deed
0,1,Roman,12,Ban Pa Sak,16.8477,100.2563,Thailand,Door Basketball Hoop,0.721255,67.803632,Volunteered at thrift store,Damaged school awards
1,2,Yui,5,The Nation / La Nation,45.3500,-75.0333,Canada,Rhythm Tambourine,0.669235,NaN,Picked up trash at playground,NaN
2,3,Kento,9,Mealhada,40.3833,-8.4500,Portugal,School House Pack,0.863656,65.154011,Organized school outdoor equipment,Stole school materials
3,4,Irina,5,Lower Pottsgrove,40.2537,-75.5975,United States,Wireless Headphones,0.701440,NaN,Helped set up band challenge,NaN
4,5,Corina,10,Bayugan,8.7100,125.7500,Philippines,Rocket Building Set,0.799672,61.740031,Helped parent with dishes,Stole school materials
5,6,Calliope,11,Castel Volturno,41.0500,13.9167,Italy,Beauty Salon Set,0.868717,72.521423,Made birthday cards for classmates,Damaged school awards
6,7,Anamaria,7,Zdzieszowice,50.4192,18.1236,Poland,Music Mixing Set,0.776364,NaN,Helped organize writing center,Cheated in tournament
7,8,Ileana,9,Tortolì,39.9333,9.6500,Italy,Cooking Master Kit,0.513277,84.732606,Made cards for librarians,Lied about occurrences
8,9,Feng,5,Svobodnyy,51.4000,128.1000,Russia,Performance Microphone,0.523516,NaN,Picked up trash at bus stop,NaN
9,10,Hui,12,Paraibuna,-23.3861,-45.6622,Brazil,Diamond Dig Set,0.614100,91.233968,Helped parent with organizing toys,Stole school supplies

In [61]:
# create a tuple of all the coordinates from the dataframe like ((x1, y1), (x2, y2), ...)
coordinates = list(zip(df_santa['X Coordinate'], df_santa['Y Coordinate']))
print(coordinates[:5])

[(16.8477, 100.2563), (45.35, -75.0333), (40.3833, -8.45), (40.2537, -75.5975), (8.71, 125.75)]

In [62]:
import numpy as np

def haversine_distance_vectorized(coords1, coords2):
    """
    Calculate the straight-line distances (in meters) between multiple geographic points using the Haversine formula.
    
    Args:
        coords1: Array of shape (n, 2) where each row is (lat, lon) in decimal degrees.
        coords2: Array of shape (n, 2) where each row is (lat, lon) in decimal degrees.

    Returns:
        Distances in meters as a 1D NumPy array.
    """
    R = 6378137  # Radius of Earth in meters

    # Convert latitude and longitude to radians
    lat1, lon1 = np.radians(coords1[:, 0]), np.radians(coords1[:, 1])
    lat2, lon2 = np.radians(coords2[:, 0]), np.radians(coords2[:, 1])

    # Compute differences
    dlat = lat2 - lat1
    dlon = lon2 - lon1

    # Haversine formula
    a = np.sin(dlat / 2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon / 2)**2
    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1 - a))

    # Distance in meters
    distances = R * c
    return distances


distances = np.zeros((len(coordinates), len(coordinates)))
# calculate the distance between all the coordinates
for i in range(len(coordinates)):
    distances[i] = haversine_distance_vectorized(np.array([coordinates[i]]), np.array(coordinates))

print(distances)

[[       0.         13097322.70901225 10312468.46371953 ...
   9315072.57111604 17141622.92788341 14027159.29165589]
 [13097322.70901225        0.          5304282.54452651 ...
   5095296.04440316  9061324.63144757  1017835.87383525]
 [10312468.46371953  5304282.54452651        0.         ...
   1556827.02704285  9804957.39461475  6077968.65084685]
 ...
 [ 9315072.57111604  5095296.04440316  1556827.02704285 ...
         0.         11224769.45474984  6036289.29819285]
 [17141622.92788341  9061324.63144757  9804957.39461475 ...
  11224769.45474984        0.          8308035.35222625]
 [14027159.29165589  1017835.87383525  6077968.65084685 ...
   6036289.29819285  8308035.35222625        0.        ]]

In [63]:
small_distances = distances.copy()
small_distances.shape

(5000, 5000)

In [64]:
route_finder = RouteAlgorithm(df_route_raw=df_santa, weighted_matrix=small_distances)
ordered_route, best_distance = route_finder.find_route_SA(view_distance=True)

KeyboardInterrupt:

In [41]:
print(ordered_route )

[19 92 95 31 90 14 84 76 67 46 43 39 63 72  6 24 71 99 20 21 56 32 66 29
 26 49 55 33 78 45 35 77  7  5 98 86 75 89 87 13 65 16 23 54 61 91 52 27
 17  2  1 28  3 64 30 68 37 58 60 82 73 59 79 50 47  9 40 11 34 81 69 38
 18 93 10 94 74  8 15 51 48 42 83 12 97  4 44 36 57 22 70 88 80  0 85 96
 53 62 25 41]

In [42]:
print(best_distance)

98740932.8804812

In [43]:
import numpy as np
from geopy.geocoders import Nominatim
import requests
import json
import folium
import dotenv
import os

In [44]:
class RouteVisualizer:
    def __init__(self, df=None, ordered_list=None):
        self.df = df
        self.ordered_list = ordered_list

    def plot_route(self, ordered_list):
        """
        Plot the route on a map using Folium.
        
        Args:
            ordered_list: List of indices representing the order of the route.
        """
        # Get the coordinates of the locations
        coords = self.df[['X Coordinate', 'Y Coordinate']].values
        coords = coords[ordered_list]

        # Get the center of the map
        center = coords.mean(axis=0)

        # Create the map
        m = folium.Map(location=center, zoom_start=12)

        # Add markers for each location
        for i, coord in enumerate(coords):
            folium.Marker(coord, popup=str(i)).add_to(m)

        # Add lines between the locations
        folium.PolyLine(coords, color="red", weight=2.5, opacity=1).add_to(m)

        return m

In [46]:
route_visualizer = RouteVisualizer(df_santa, ordered_route)
m = route_visualizer.plot_route(ordered_route)
m.save('route.html')